name: cache-workflow

on:
  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: restore-cache
        id: cache-b666c9e
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: cache-b666c9e

      - name: prime-cache-b666c9e
        run: |
          if [ "${{ steps.cache-b666c9e.outputs.cache-hit }}" = 'true' ]; then
            echo "CACHE HIT"
          else
            echo "CACHE MISS"
            mkdir -p ~/.cache/demo
            echo hello > ~/.cache/demo/file.txt
          fi
