name: email-check
on: [workflow_dispatch] # This allows you to run it manually

jobs:
  check-email:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3002424@ds.study.iitm.ac.in
        run: echo "Verified email step"
